# Libraries

In [41]:
# Core Libraries 
import pandas as pd
import numpy as np
import requests

# For Pattern
import re

# For Yahoo Data Sets
import yfinance as yf

* Libraries Version

In [42]:
print(f"Pandas Version: {pd.__version__} \n ----")
print(f"Numpy Version: {np.__version__}\n ----")
print(f"Re Version: {re.__version__}\n ----")
print(f"yfinance Version: {yf.__version__}\n ----")
print(f"Requests Version: {requests.__version__}")

Pandas Version: 2.0.2
 ----
Numpy Version: 1.22.3
 ----
Re Version: 2.2.1
 ----
yfinance Version: 0.2.26
 ----
Requests Version: 2.31.0

# Alpha Vantage Data Set

[AlphaVantage Website](https://www.alphavantage.co/documentation/)

* Also, you can check Api Key Requests

## API KEY Configuration

* API keys hidden for security !!!

In [43]:
#for Api Key --- AlphaVantage Api Key  (https://www.alphavantage.co/)
from dotenv import load_dotenv
import os

def configure():
    load_dotenv()

## Alpha Vantage Financial Statements

1. FS[0] = Income Statement

2. FS[1] = Balance Sheet

3. FS[2] = Cashflow

In [44]:
ticker = "AAPL"

In [45]:

FS = ["INCOME_STATEMENT","BALANCE_SHEET","CASH_FLOW"]   # Financial Statements

data = []
IS = {}                                                 # Income Statements
BS = {}                                                 # Balance Sheet
CF = {}                                                 # Cash Flow


for i in FS:
    url = f'https://www.alphavantage.co/query?function={i}&symbol={ticker}&apikey={os.getenv("Alphavantage_key")}'
    r = requests.get(url)
    data.append(r.json())

    data_df = pd.DataFrame(data)
    
    df = {}
    for i in np.arange(0, len(data_df)):
        df[i] = data_df.iloc[i].get("annualReports")

IS = pd.DataFrame(df[0]).T.reset_index()
BS = pd.DataFrame(df[1]).T.reset_index()
CF = pd.DataFrame(df[2]).T.reset_index()

FS = [IS,BS,CF]

IS_fiscal_Date = IS.iloc[0].to_list()
IS_index = IS.iloc[1].to_list()

FS_pattern = []

for i in np.arange(0, len(FS)):
    FS[i].replace("None",0,inplace = True)
    FS[i].fillna(0)

    FS[i].copy
    FS[i].loc[2:,[0,1,2,3,4]] = FS[i].loc[2:,[0,1,2,3,4]].astype("float64")
    
    FS[i].loc[:1] = IS_fiscal_Date
    FS[i].loc[1] = IS_index
    
    FS_pattern.append(FS[i]["index"])

pattern_list = pd.DataFrame()

IS = FS_pattern[0]
two = FS_pattern[1]
three = FS_pattern[2]

pat_list = [IS,two,three]

pattern = '[A-Z][^A-Z]*|[A-Z]*[^A-Z][^A-Z]*|[A-Z]*[^A-Z][^A-Z][^A-Z]*|[A-Z]*[^A-Z][^A-Z][^A-Z][^A-Z]*'

FS_0_join = []
for i in np.arange(0, len(IS)):
    FS_0_pattern = IS[i]
    FS_0_findall = re.findall(pattern,FS_0_pattern)
    FS_0_join.append(" ".join(FS_0_findall).title())
FS[0]["index"] = FS_0_join

FS_1_join = []
for z in np.arange(0, len(two)):
    FS_1_pattern = two[z]
    FS_1_findall = re.findall(pattern,FS_1_pattern)
    FS_1_join.append(" ".join(FS_1_findall).title())
FS[1]["index"] = FS_1_join

FS_2_join = []
for q in np.arange(0, len(three)):
    FS_2_pattern = three[q]
    FS_2_findall = re.findall(pattern,FS_2_pattern)
    FS_2_join.append(" ".join(FS_2_findall).title())
FS[2]["index"] = FS_2_join

index_names = ["INCOME STATEMENT","BALANCE SHEET","CASH FLOW"]

for i in np.arange(0,3):
    FS[i].columns = IS_fiscal_Date
    FS[i] = FS[i].drop(0)

    FS[i].index.name = index_names[i]

display(FS[0])
display(FS[1])
display(FS[2])

,fiscalDateEnding,2022-09-30,2021-09-30,2020-09-30,2019-09-30,2018-09-30
INCOME STATEMENT,,,,,,
1,Reported Currency,USD,USD,USD,USD,USD
2,Gross Profit,170782000000.0,152836000000.0,104956000000.0,98392000000.0,101839000000.0
3,Total Revenue,391397000000.0,363172000000.0,271642000000.0,256598000000.0,265595000000.0
4,Cost Of Revenue,248640000000.0,234954000000.0,189475000000.0,180027000000.0,163756000000.0
5,Costof Goods And Services Sold,223546000000.0,212981000000.0,169559000000.0,161782000000.0,163756000000.0
6,Operating Income,119437000000.0,108949000000.0,66288000000.0,63930000000.0,70898000000.0
7,Selling General And Administrative,25094000000.0,21973000000.0,19916000000.0,18245000000.0,16705000000.0
8,Research And Development,26251000000.0,21914000000.0,18752000000.0,16217000000.0,14236000000.0
9,Operating Expenses,51345000000.0,43887000000.0,38668000000.0,34462000000.0,30941000000.0
10,Investment Income Net,2825000000.0,2843000000.0,3763000000.0,4961000000.0,5686000000.0
11,Net Interest Income,-2931000000.0,-2645000000.0,-2873000000.0,-3576000000.0,-3240000000.0
12,Interest Income,106000000.0,2843000000.0,3763000000.0,4961000000.0,5686000000.0
13,Interest Expense,2931000000.0,2645000000.0,2873000000.0,3576000000.0,3240000000.0
14,Non Interest Income,394328000000.0,365817000000.0,274515000000.0,260174000000.0,265595000000.0
15,Other Non Operating Income,-228000000.0,60000000.0,-87000000.0,422000000.0,-441000000.0
16,Depreciation,8700000000.0,9500000000.0,9700000000.0,11300000000.0,9300000000.0
17,Depreciation And Amortization,11104000000.0,11284000000.0,11056000000.0,12547000000.0,10903000000.0
18,Income Before Tax,119103000000.0,109207000000.0,67091000000.0,65737000000.0,72903000000.0
19,Income Tax Expense,19300000000.0,14527000000.0,9680000000.0,10481000000.0,13372000000.0
20,Interest And Debt Expense,2931000000.0,2645000000.0,2873000000.0,3576000000.0,3240000000.0
21,Net Income From Continuing Operations,99803000000.0,94680000000.0,57411000000.0,55256000000.0,59531000000.0
22,Comprehensive Income Net Of Tax,88531000000.0,95249000000.0,57453000000.0,58037000000.0,56505000000.0
23,Ebit,122034000000.0,111852000000.0,69964000000.0,69313000000.0,76143000000.0
24,Ebitda,130541000000.0,120233000000.0,77344000000.0,76477000000.0,81801000000.0
25,Net Income,99803000000.0,94680000000.0,57411000000.0,55256000000.0,59531000000.0

,fiscalDateEnding,2022-09-30,2021-09-30,2020-09-30,2019-09-30,2018-09-30
BALANCE SHEET,,,,,,
1,Reported Currency,USD,USD,USD,USD,USD
2,Total Assets,352755000000.0,351002000000.0,323888000000.0,338516000000.0,365725000000.0
3,Total Current Assets,135405000000.0,134836000000.0,143713000000.0,162819000000.0,131339000000.0
4,Cash And Cash Equivalents At Carrying Value,23646000000.0,34940000000.0,38016000000.0,48844000000.0,25913000000.0
5,Cash And Short Term Investments,48304000000.0,62639000000.0,90943000000.0,100557000000.0,25913000000.0
6,Inventory,4946000000.0,6580000000.0,4061000000.0,4106000000.0,3956000000.0
7,Current Net Receivables,60932000000.0,51506000000.0,37445000000.0,45804000000.0,48995000000.0
8,Total Non Current Assets,217350000000.0,216166000000.0,180175000000.0,175697000000.0,234386000000.0
9,Property Plant Equipment,42117000000.0,39440000000.0,36766000000.0,37378000000.0,41304000000.0
10,Accumulated Depreciation Amortization P P E,72340000000.0,70283000000.0,66760000000.0,58579000000.0,49099000000.0
11,Intangible Assets,0.0,0.0,0.0,0.0,0.0
12,Intangible Assets Excluding Goodwill,0.0,0.0,0.0,0.0,0.0
13,Goodwill,0.0,0.0,0.0,0.0,0.0
14,Investments,292870000000.0,318994000000.0,345644000000.0,362952000000.0,448287000000.0
15,Long Term Investments,120805000000.0,127877000000.0,100887000000.0,105341000000.0,170799000000.0
16,Short Term Investments,24658000000.0,27699000000.0,52927000000.0,51713000000.0,40388000000.0
17,Other Current Assets,21223000000.0,14111000000.0,11264000000.0,12352000000.0,12087000000.0
18,Other Non Current Assets,54428000000.0,48849000000.0,42522000000.0,32978000000.0,22283000000.0
19,Total Liabilities,302083000000.0,287912000000.0,258549000000.0,248028000000.0,258578000000.0
20,Total Current Liabilities,153982000000.0,125481000000.0,105392000000.0,105718000000.0,115929000000.0
21,Current Accounts Payable,64115000000.0,54763000000.0,42296000000.0,46236000000.0,55888000000.0
22,Deferred Revenue,20312000000.0,19512000000.0,16843000000.0,13622000000.0,14766000000.0
23,Current Debt,21239000000.0,15692000000.0,13793000000.0,16240000000.0,20748000000.0
24,Short Term Debt,9982000000.0,6000000000.0,4996000000.0,5980000000.0,11964000000.0
25,Total Non Current Liabilities,148101000000.0,162431000000.0,153157000000.0,142310000000.0,142649000000.0
26,Capital Lease Obligations,812000000.0,769000000.0,637000000.0,0.0,0.0
27,Long Term Debt,110100000000.0,118700000000.0,125873000000.0,117760000000.0,111984000000.0
28,Current Long Term Debt,11128000000.0,9613000000.0,8773000000.0,10260000000.0,8784000000.0
29,Long Term Debt Noncurrent,98959000000.0,109106000000.0,98667000000.0,91807000000.0,93735000000.0
30,Short Long Term Debt Total,233256000000.0,241783000000.0,216860000000.0,209135000000.0,220132000000.0
31,Other Current Liabilities,60845000000.0,47493000000.0,42684000000.0,37720000000.0,33327000000.0
32,Other Non Current Liabilities,49142000000.0,53325000000.0,54490000000.0,50503000000.0,48914000000.0
33,Total Shareholder Equity,50672000000.0,63090000000.0,65339000000.0,90488000000.0,107147000000.0
34,Treasury Stock,0.0,0.0,0.0,0.0,0.0
35,Retained Earnings,-3068000000.0,5562000000.0,14966000000.0,45898000000.0,70400000000.0
36,Common Stock,64849000000.0,57365000000.0,50779000000.0,45174000000.0,40201000000.0
37,Common Stock Shares Outstanding,15943425000.0,16426786000.0,16976763000.0,4443236000.0,4754986000.0

,fiscalDateEnding,2022-09-30,2021-09-30,2020-09-30,2019-09-30,2018-09-30
CASH FLOW,,,,,,
1,Reported Currency,USD,USD,USD,USD,USD
2,Operating Cashflow,122151000000.0,104038000000.0,80674000000.0,69391000000.0,77434000000.0
3,Payments For Operating Activities,4665000000.0,4087000000.0,4502000000.0,3423000000.0,3022000000.0
4,Proceeds From Operating Activities,0.0,0.0,0.0,0.0,0.0
5,Change In Operating Liabilities,15558000000.0,19801000000.0,6935000000.0,-7248000000.0,47665000000.0
6,Change In Operating Assets,14358000000.0,24712000000.0,1245000000.0,-3760000000.0,12927000000.0
7,Depreciation Depletion And Amortization,11104000000.0,11284000000.0,11056000000.0,12547000000.0,10903000000.0
8,Capital Expenditures,10708000000.0,11085000000.0,7309000000.0,10495000000.0,13313000000.0
9,Change In Receivables,9343000000.0,14028000000.0,-8470000000.0,-3176000000.0,13332000000.0
10,Change In Inventory,-1484000000.0,2642000000.0,127000000.0,289000000.0,-828000000.0
11,Profit Loss,99803000000.0,94680000000.0,57411000000.0,55256000000.0,59531000000.0
12,Cashflow From Investment,-22354000000.0,-14545000000.0,-4289000000.0,45896000000.0,16066000000.0
13,Cashflow From Financing,-110749000000.0,-93353000000.0,-86820000000.0,-90976000000.0,-87876000000.0
14,Proceeds From Repayments Of Short Term Debt,7910000000.0,2044000000.0,-1926000000.0,-11954000000.0,-74000000.0
15,Payments For Repurchase Of Common Stock,89402000000.0,85971000000.0,72358000000.0,66897000000.0,72738000000.0
16,Payments For Repurchase Of Equity,89402000000.0,85971000000.0,72358000000.0,66897000000.0,72738000000.0
17,Payments For Repurchase Of Preferred Stock,0.0,0.0,0.0,0.0,0.0
18,Dividend Payout,14841000000.0,14467000000.0,14081000000.0,14119000000.0,13712000000.0
19,Dividend Payout Common Stock,14841000000.0,14467000000.0,14081000000.0,14119000000.0,13712000000.0
20,Dividend Payout Preferred Stock,0.0,0.0,0.0,0.0,0.0
21,Proceeds From Issuance Of Common Stock,0.0,1105000000.0,880000000.0,781000000.0,669000000.0
22,Proceeds From Issuance Of Long Term Debt And C...,5465000000.0,20393000000.0,16091000000.0,6963000000.0,6969000000.0
23,Proceeds From Issuance Of Preferred Stock,0.0,0.0,0.0,0.0,0.0
24,Proceeds From Repurchase Of Equity,-89402000000.0,-84866000000.0,-71478000000.0,-66116000000.0,-72069000000.0
25,Proceeds From Sale Of Treasury Stock,0.0,0.0,0.0,0.0,0.0
26,Change In Cash And Cash Equivalents,-10952000000.0,-3860000000.0,-10435000000.0,24311000000.0,5624000000.0
27,Change In Exchange Rate,0.0,0.0,0.0,0.0,0.0
28,Net Income,99803000000.0,94680000000.0,57411000000.0,55256000000.0,59531000000.0

In [46]:
IS = FS[0]
IS = IS.iloc[1:]
IS = IS.reset_index(drop = True)
IS.index.name = "IncomeStatement" 
IS.columns = ["Title","Year2022","Year2021","Year2020","Year2019","Year2018"]
IS[["Year2022","Year2021","Year2020","Year2019","Year2018"]] = IS[["Year2022","Year2021","Year2020","Year2019","Year2018"]].astype(float)
BS = FS[1]
BS = BS.iloc[1:]
BS = BS.reset_index(drop = True)
BS.index.name = "BalanceSheet"
BS.columns = ["Title","Year2022","Year2021","Year2020","Year2019","Year2018"]
BS[["Year2022","Year2021","Year2020","Year2019","Year2018"]] = BS[["Year2022","Year2021","Year2020","Year2019","Year2018"]].astype(float)
CF = FS[2]
CF = CF.iloc[1:]
CF = CF.reset_index(drop = True)
CF.index.name = "CashFlow"
CF.columns = ["Title","Year2022","Year2021","Year2020","Year2019","Year2018"]
CF[["Year2022","Year2021","Year2020","Year2019","Year2018"]] = CF[["Year2022","Year2021","Year2020","Year2019","Year2018"]].astype(float)

# Yahoo Finance Data Sets

[Yahoo Finance Website](https://pypi.org/project/yfinance/)

## Data Sets

In [47]:
Apple= yf.download("AAPL")  
Apple

[*********************100%***********************]  1 of 1 completed

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
1980-12-12,0.128348,0.128906,0.128348,0.128348,0.099450,469033600
1980-12-15,0.122210,0.122210,0.121652,0.121652,0.094261,175884800
1980-12-16,0.113281,0.113281,0.112723,0.112723,0.087343,105728000
1980-12-17,0.115513,0.116071,0.115513,0.115513,0.089504,86441600
1980-12-18,0.118862,0.119420,0.118862,0.118862,0.092099,73449600
...,...,...,...,...,...,...
2023-09-01,189.490005,189.919998,188.279999,189.460007,189.460007,45732600
2023-09-05,188.279999,189.979996,187.610001,189.699997,189.699997,45280000
2023-09-06,188.399994,188.850006,181.470001,182.910004,182.910004,81755800
2023-09-07,175.179993,178.210007,173.539993,177.559998,177.559998,112488800
2023-09-08,178.350006,180.240005,177.789993,178.179993,178.179993,65551300

* Company Information

In [48]:
AAPL = yf.Ticker("AAPL")

info_keys = AAPL.info.keys()          # Company information

AAPL_info = []

for i in info_keys:
    v = AAPL.info.get(i)
    AAPL_info.append(v)
AAPL_info = pd.DataFrame(AAPL_info, index = info_keys, columns=["Information"])
AAPL_info.index.name = "Title"

AAPL_info

                          Information
Title
address1           One Apple Park Way
city                        Cupertino
state                              CA
zip                             95014
country                 United States
...                               ...
grossMargins                  0.43449
ebitdaMargins                 0.32286
operatingMargins              0.29231
financialCurrency                 USD
trailingPegRatio               2.2695

[130 rows x 1 columns]

In [49]:
CompanyName = AAPL_info[AAPL_info.index == "longName"]
CompanyName = CompanyName["Information"].values[0]
CompanyName

'Apple Inc.'

In [50]:
Website = AAPL_info[AAPL_info.index == "website"]
Website = Website["Information"].values[0]
Website

'https://www.apple.com'

In [51]:
Country = AAPL_info[AAPL_info.index == "country"]
Country = Country["Information"].values[0]
Country

'United States'

In [52]:
Industry = AAPL_info[AAPL_info.index == "industry"]
Industry = Industry["Information"].values[0]
Industry

'Consumer Electronics'

In [53]:
Sector = AAPL_info[AAPL_info.index == "sector"]
Sector = Sector["Information"].values[0]
Sector

'Technology'

In [54]:
FinancialCurrency = AAPL_info[AAPL_info.index == "financialCurrency"]
FinancialCurrency = FinancialCurrency["Information"].values[0]
FinancialCurrency

'USD'

In [55]:
Info = AAPL_info[AAPL_info.index == "longBusinessSummary"]
Info = Info["Information"].values[0]
Info

'Apple Inc. designs, manufactures, and markets smartphones, personal computers, tablets, wearables, and accessories worldwide. The company offers iPhone, a line of smartphones; Mac, a line of personal computers; iPad, a line of multi-purpose tablets; and wearables, home, and accessories comprising AirPods, Apple TV, Apple Watch, Beats products, and HomePod. It also provides AppleCare support and cloud services; and operates various platforms, including the App Store that allow customers to discover and download applications and digital content, such as books, music, video, games, and podcasts. In addition, the company offers various services, such as Apple Arcade, a game subscription service; Apple Fitness+, a personalized fitness service; Apple Music, which offers users a curated listening experience with on-demand radio stations; Apple News+, a subscription news and magazine service; Apple TV+, which offers exclusive original content; Apple Card, a co-branded credit card; and Apple Pay, a cashless payment service, as well as licenses its intellectual property. The company serves consumers, and small and mid-sized businesses; and the education, enterprise, and government markets. It distributes third-party applications for its products through the App Store. The company also sells its products through its retail and online stores, and direct sales force; and third-party cellular network carriers, wholesalers, retailers, and resellers. Apple Inc. was incorporated in 1977 and is headquartered in Cupertino, California.'

In [56]:
SummaryOfInfo = pd.DataFrame({"Company Name":[CompanyName], "Website":[Website],"Country":[Country],
                              "Industry":[Industry],"Sector":[Sector],"Financial Currency":[FinancialCurrency]})
SummaryOfInfo.T

                                        0
Company Name                   Apple Inc.
Website             https://www.apple.com
Country                     United States
Industry             Consumer Electronics
Sector                         Technology
Financial Currency                    USD

In [72]:
remove = ["address1","city","state","zip","country","phone","website","industry","industryDisp","sector",
          "sectorDisp","longBusinessSummary","fullTimeEmployees","companyOfficers","currency","symbol","underlyingSymbol",
          "shortName","longName","uuid","messageBoardId","financialCurrency"]

AAPL_info_new = AAPL_info.drop(remove)
AAPL_info_new

                      Information
Title
auditRisk                       4
boardRisk                       1
compensationRisk                5
shareHolderRightsRisk           1
overallRisk                     1
...                           ...
revenueGrowth              -0.014
grossMargins              0.43449
ebitdaMargins             0.32286
operatingMargins          0.29231
trailingPegRatio           2.2695

[108 rows x 1 columns]

In [73]:
Appleindex = AAPL_info_new.index.to_list()

pattern = '[A-Z][^A-Z]*|[A-Z]*[^A-Z][^A-Z]*|[A-Z]*[^A-Z][^A-Z][^A-Z]*|[A-Z]*[^A-Z][^A-Z][^A-Z][^A-Z]*'

In [74]:
AppleTitle = []

for i in np.arange(0, len(Appleindex)):
    patternlist = Appleindex[i]
    findall = re.findall(pattern,patternlist)
    AppleTitle.append(" ".join(findall).title())
AppleTitle

['Audit Risk',
 'Board Risk',
 'Compensation Risk',
 'Share Holder Rights Risk',
 'Overall Risk',
 'Governance Epoch Date',
 'Compensation As Of Epoch Date',
 'Max Age',
 'Price Hint',
 'Previous Close',
 'Open',
 'Day Low',
 'Day High',
 'Regular Market Previous Close',
 'Regular Market Open',
 'Regular Market Day Low',
 'Regular Market Day High',
 'Dividend Rate',
 'Dividend Yield',
 'Ex Dividend Date',
 'Payout Ratio',
 'Five Year Avg Dividend Yield',
 'Beta',
 'Trailing P E',
 'Forward P E',
 'Volume',
 'Regular Market Volume',
 'Average Volume',
 'Average Volume10Days',
 'Average Daily Volume10 Day',
 'Bid',
 'Ask',
 'Bid Size',
 'Ask Size',
 'Market Cap',
 'Fifty Two Week Low',
 'Fifty Two Week High',
 'Price To Sales Trailing12 Months',
 'Fifty Day Average',
 'Two Hundred Day Average',
 'Trailing Annual Dividend Rate',
 'Trailing Annual Dividend Yield',
 'Enterprise Value',
 'Profit Margins',
 'Float Shares',
 'Shares Outstanding',
 'Shares Short',
 'Shares Short Prior Month',
 'Shares Short Previous Month Date',
 'Date Short Interest',
 'Shares Percent Shares Out',
 'Held Percent Insiders',
 'Held Percent Institutions',
 'Short Ratio',
 'Short Percent Of Float',
 'Implied Shares Outstanding',
 'Book Value',
 'Price To Book',
 'Last Fiscal Year End',
 'Next Fiscal Year End',
 'Most Recent Quarter',
 'Earnings Quarterly Growth',
 'Net Income To Common',
 'Trailing Eps',
 'Forward Eps',
 'Peg Ratio',
 'Last Split Factor',
 'Last Split Date',
 'Enterprise To Revenue',
 'Enterprise To Ebitda',
 '52 Week Change',
 'Sand P52 Week Change',
 'Last Dividend Value',
 'Last Dividend Date',
 'Exchange',
 'Quote Type',
 'First Trade Date Epoch Utc',
 'Time Zone Full Name',
 'Time Zone Short Name',
 'Gmt Off Set Milliseconds',
 'Current Price',
 'Target High Price',
 'Target Low Price',
 'Target Mean Price',
 'Target Median Price',
 'Recommendation Mean',
 'Recommendation Key',
 'Number Of Analyst Opinions',
 'Total Cash',
 'Total Cash Per Share',
 'Ebitda',
 'Total Debt',
 'Quick Ratio',
 'Current Ratio',
 'Total Revenue',
 'Debt To Equity',
 'Revenue Per Share',
 'Return On Assets',
 'Return On Equity',
 'Gross Profits',
 'Free Cashflow',
 'Operating Cashflow',
 'Earnings Growth',
 'Revenue Growth',
 'Gross Margins',
 'Ebitda Margins',
 'Operating Margins',
 'Trailing Peg Ratio']

In [75]:
AAPL_info_new.index = AppleTitle
AAPL_info_new

                         Information
Audit Risk                         4
Board Risk                         1
Compensation Risk                  5
Share Holder Rights Risk           1
Overall Risk                       1
...                              ...
Revenue Growth                -0.014
Gross Margins                0.43449
Ebitda Margins               0.32286
Operating Margins            0.29231
Trailing Peg Ratio            2.2695

[108 rows x 1 columns]

In [1]:
Company_symbol = yf.Ticker("C")

Company_example = pd.DataFrame(Company_symbol.balance_sheet)
Company_example

,2022-12-31,2021-12-31,2020-12-31,2019-12-31
Treasury Shares Number,1162816560.0,1115296641.0,1017674452.0,985479501.0
Preferred Shares Number,97800000.0,97800000.0,NaN,NaN
Ordinary Shares Number,1936852864.0,1984355194.0,2082089209.0,2114123355.0
Share Issued,3099669424.0,3099651835.0,3099763661.0,3099602856.0
Net Debt,NaN,20314000000.0,NaN,99890000000.0
Total Debt,318702000000.0,282347000000.0,301200000000.0,293809000000.0
Tangible Book Value,158075000000.0,157183000000.0,153376000000.0,148314000000.0
Invested Capital,500896000000.0,465324000000.0,481485000000.0,469071000000.0
Net Tangible Assets,177070000000.0,176178000000.0,172856000000.0,166294000000.0
Common Stock Equity,182194000000.0,182977000000.0,180285000000.0,175262000000.0
Preferred Stock Equity,18995000000.0,18995000000.0,19480000000.0,17980000000.0
Total Capitalization,472795000000.0,456346000000.0,471451000000.0,442002000000.0
Total Equity Gross Minority Interest,201838000000.0,202672000000.0,200523000000.0,193946000000.0
Minority Interest,649000000.0,700000000.0,758000000.0,704000000.0
Stockholders Equity,201189000000.0,201972000000.0,199765000000.0,193242000000.0
Gains Losses Not Affecting Retained Earnings,-47062000000.0,-38765000000.0,-32058000000.0,-36318000000.0
Treasury Stock,73967000000.0,71240000000.0,64129000000.0,61660000000.0
Retained Earnings,194734000000.0,184948000000.0,168595000000.0,165369000000.0
Additional Paid In Capital,108458000000.0,108003000000.0,107846000000.0,107840000000.0
Capital Stock,19026000000.0,19026000000.0,19511000000.0,18011000000.0
Common Stock,31000000.0,31000000.0,31000000.0,31000000.0
Preferred Stock,18995000000.0,18995000000.0,19480000000.0,17980000000.0
Total Liabilities Net Minority Interest,2214838000000.0,2088741000000.0,2059798000000.0,1757212000000.0
Long Term Debt And Capital Lease Obligation,271606000000.0,254374000000.0,271686000000.0,248760000000.0
Long Term Debt,271606000000.0,254374000000.0,271686000000.0,248760000000.0
Long Term Provisions,2151000000.0,2655000000.0,NaN,NaN
Current Debt And Capital Lease Obligation,47096000000.0,27973000000.0,29514000000.0,45049000000.0
Current Debt,47096000000.0,27973000000.0,29514000000.0,45049000000.0
Other Current Borrowings,47096000000.0,27973000000.0,29514000000.0,45049000000.0
Commercial Paper,25530000000.0,16018000000.0,18010000000.0,16476000000.0
Payables And Accrued Expenses,69218000000.0,61430000000.0,50484000000.0,48601000000.0
Payables,69218000000.0,61430000000.0,50484000000.0,48601000000.0
Other Payable,NaN,NaN,39319000000.0,37613000000.0
Accounts Payable,69218000000.0,61430000000.0,50484000000.0,48601000000.0
Total Assets,2416676000000.0,2291413000000.0,2260321000000.0,1951158000000.0
Investments And Advances,860696000000.0,844767000000.0,822438000000.0,644703000000.0
Held To Maturity Securities,268863000000.0,216963000000.0,104943000000.0,80775000000.0
Available For Sale Securities,8040000000.0,7337000000.0,7332000000.0,7523000000.0
Trading Securities,334114000000.0,331945000000.0,375079000000.0,276140000000.0
Goodwill And Other Intangible Assets,24119000000.0,25794000000.0,26909000000.0,26948000000.0
Other Intangible Assets,4428000000.0,4495000000.0,4747000000.0,4822000000.0
Goodwill,19691000000.0,21299000000.0,22162000000.0,22126000000.0
Net PPE,26253000000.0,NaN,NaN,NaN
Receivables,54192000000.0,54340000000.0,44806000000.0,39857000000.0
Other Receivables,354000000.0,54340000000.0,44806000000.0,39857000000.0
Accounts Receivable,54192000000.0,54340000000.0,44806000000.0,39857000000.0
Other Short Term Investments,249679000000.0,288522000000.0,335084000000.0,280265000000.0
Cash And Cash Equivalents,342025000000.0,262033000000.0,309615000000.0,193919000000.0
Cash Financial,30577000000.0,27515000000.0,26349000000.0,23967000000.0